name: Terraform Githug Actions
on: 
 workflow_dispatch:
   inputs:
     service_name:
       type: choice
       description: 'Choose the service name'
       options:
       - exercise1
       - exercise2
       - exercise3
       - exercise4
       - exercise5
     action:
       type: choice
       description: 'Which action do you want to perform?'
       options:
       - plan
       - apply -auto-approve
       - destroy -auto-approve
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout Code
     uses: actions/checkout@v2
   - name: AWS Credentials
     uses: aws-actions/configure-aws-credentials@v1
     with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
   - name: Terraform init
     env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KE  Y: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
     run:  |
       echo "Hello"
       pwd
       ls
       cd exercises
       cd ${{ github.event.inputs.service_name }}
       pwd
       terraform init
   - name: Terraform ${{ github.event.inputs.action }}
     env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
     run:  |
       pwd
       cd exercises
       cd ${{ github.event.inputs.service_name }}
       terraform ${{ github.event.inputs.action }}
